./noisify noisfy_trials/inp0.jpg noisfy_trials/out0.jpg
./noisify noisfy_trials/inp1.jpg noisfy_trials/out1.jpg
./noisify noisfy_trials/inp2.jpg noisfy_trials/out2.jpg
./noisify noisfy_trials/inp3.jpg noisfy_trials/out3.jpg
./noisify noisfy_trials/inp4.jpg noisfy_trials/out4.jpg
./noisify noisfy_trials/inp5.jpg noisfy_trials/out5.jpg
./noisify noisfy_trials/inp6.jpg noisfy_trials/out6.jpg
./noisify noisfy_trials/inp7.jpg noisfy_trials/out7.jpg
./noisify noisfy_trials/inp8.jpg noisfy_trials/out8.jpg
./noisify noisfy_trials/inp9.jpg noisfy_trials/out9.jpg
./noisify noisfy_trials/inp10.jpg noisfy_trials/out10.jpg
./noisify noisfy_trials/inp11.jpg noisfy_trials/out11.jpg
./noisify noisfy_trials/inp12.jpg noisfy_trials/out12.jpg
./noisify noisfy_trials/inp13.jpg noisfy_trials/out13.jpg
./noisify noisfy_trials/inp14.jpg noisfy_trials/out14.jpg
./noisify noisfy_trials/inp15.jpg noisfy_trials/out15.jpg
./noisify noisfy_trials/inp16.jpg noisfy_trials/out16.jpg
./noisify noisfy_trials/inp17.jpg noisfy_trials/out17.jpg
./noisify noisfy_trials/inp18.jpg noisfy_trials/out18.jpg
./noisify noisfy_trials/inp19.jpg noisfy_trials/out19.jpg
